apiVersion: v1
kind: Service
metadata:
  name: metadata-store-service
  namespace: dkv
  labels:
    app: metadata-store
spec:
  clusterIP: None  # Headless Service for stable DNS
  ports:
    - port: 9000
      name: dkv-port
      targetPort: 9000
    - port: 9091
      name: metrics-port
      targetPort: 9091
  selector:
    app: metadata-store
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metadata-store
  namespace: dkv
  labels:
    app: metadata-store
spec:
  serviceName: metadata-store-service
  replicas: 1
  selector:
    matchLabels:
      app: metadata-store
  template:
    metadata:
      labels:
        app: metadata-store
    spec:
      containers:
        - name: metadata-store
          image: us-central1-docker.pkg.dev/project-1227447b-a30c-4990-bb3/dkv-repo/kvsrvd:latest
          imagePullPolicy: Always
          command: ["/usr/local/bin/server"]
          args:
            - "--addr"
            - ":9000"
            - "--metrics-addr"
            - ":9091"
          ports:
            - containerPort: 9000
              name: dkv-port
            - containerPort: 9091
              name: metrics-port
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
