apiVersion: v1
kind: Service
metadata:
  name: shardctrlr-service
  namespace: dkv
  labels:
    app: shardctrlr
spec:
  ports:
    - port: 9100
      name: dkv-port
      targetPort: 9100
    - port: 9091
      name: metrics-port
      targetPort: 9091
  selector:
    app: shardctrlr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shardctrlr
  namespace: dkv
  labels:
    app: shardctrlr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shardctrlr
  template:
    metadata:
      labels:
        app: shardctrlr
    spec:
      containers:
        - name: shardctrlr
          image: us-central1-docker.pkg.dev/project-1227447b-a30c-4990-bb3/dkv-repo/shardctrlrd:latest
          imagePullPolicy: Always
          command: ["/usr/local/bin/server"]
          args:
            - "--kvsrv-addr"
            - "metadata-store-0.metadata-store-service.dkv.svc.cluster.local:9000"
            - "--groups"
            - "1=kvraft-1-0.kvraft-1-service.dkv.svc.cluster.local:8000,kvraft-1-1.kvraft-1-service.dkv.svc.cluster.local:8000,kvraft-1-2.kvraft-1-service.dkv.svc.cluster.local:8000;2=kvraft-2-0.kvraft-2-service.dkv.svc.cluster.local:8010,kvraft-2-1.kvraft-2-service.dkv.svc.cluster.local:8010,kvraft-2-2.kvraft-2-service.dkv.svc.cluster.local:8010"
            - "--metrics-addr"
            - ":9091"
          ports:
            - containerPort: 9100
              name: dkv-port
            - containerPort: 9091
              name: metrics-port
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
