apiVersion: v1
kind: Service
metadata:
  name: kvraft-2-service
  namespace: dkv
  labels:
    app: kvraft-2
spec:
  clusterIP: None  # Headless Service for stable DNS
  ports:
    - port: 8010
      name: dkv-port
      targetPort: 8010
    - port: 9091
      name: metrics-port
      targetPort: 9091
  selector:
    app: kvraft-2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kvraft-2
  namespace: dkv
  labels:
    app: kvraft-2
spec:
  serviceName: kvraft-2-service
  replicas: 3
  selector:
    matchLabels:
      app: kvraft-2
  template:
    metadata:
      labels:
        app: kvraft-2
    spec:
      affinity:
        # Guarantee zone-level redundancy by spreading pods across zones
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - kvraft-2
              topologyKey: "topology.kubernetes.io/zone"
      containers:
        - name: kvraft-2
          image: us-central1-docker.pkg.dev/project-1227447b-a30c-4990-bb3/dkv-repo/kvraftd:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              POD_INDEX=$(hostname | awk -F'-' '{print $NF}')
              echo "Starting Shard Group 2 Replica ID: ${POD_INDEX}"
              exec /usr/local/bin/server \
                --me "${POD_INDEX}" \
                --peers "kvraft-2-0.kvraft-2-service.dkv.svc.cluster.local:8010,kvraft-2-1.kvraft-2-service.dkv.svc.cluster.local:8010,kvraft-2-2.kvraft-2-service.dkv.svc.cluster.local:8010" \
                --gid "2" \
                --persist-dir "/var/lib/raft" \
                --metrics-addr ":9091"
          ports:
            - containerPort: 8010
              name: dkv-port
            - containerPort: 9091
              name: metrics-port
          volumeMounts:
            - name: raft-state
              mountPath: /var/lib/raft
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  volumeClaimTemplates:
    - metadata:
        name: raft-state
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: premium-rwo  # High-performance SSD on GCP GKE
        resources:
          requests:
            storage: 10Gi
